# Generated by Django 3.0.8 on 2020-07-10 20:13

from django.db import migrations, models
import ebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ebook.models.upload_location)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=ebook.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('sulg', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
