# Generated by Django 3.1 on 2020-08-22 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ebook.models.upload_location)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=ebook.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('likes', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
