# Generated by Django 3.0.8 on 2020-07-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebookpost',
            old_name='sulg',
            new_name='slug',
        ),
    ]
